/**
 * DO NOT EDIT THIS FILE.
 * See the following change record for more information,
 * https://www.drupal.org/node/2815083
 * @preserve
			// END
 **/

(function ($, Drupal, drupalSettings) {	
	Drupal.behaviors.raCustomUtility = {
		attach: function (context, settings) {
			setTimeout(function(){
				/*$( "tr.single-day>td>div>div>div>div>div.contents" ).each(function( index ) {
					var parentDiv=$(this).parent().parent().parent().parent().parent();
					var clsd = parentDiv.find('.'+$( this ).attr('class').split(" ")[0]).length;
					console.log(parentDiv.attr('classs'));
					console.log(parentDiv.find('.'+$( this ).attr('class').split(" ")[0]));
					if(clsd>1){
						var cls = '.' + $( this ).attr('class').split(" ")[0]+".contents";
						$(cls).each(function(index) {
							if(index>0){
								$(this).hide();
							}
						});
					}
				});*/
				$( "tr.single-day>td" ).each(function( ) {
					var current_data_td = $(this).attr('id');
					var currenttd = $(this);
					$( "td#"+current_data_td+">div>div>div>div>div.contents" ).each(function(  ) {
						var parentDiv=$(this).parent().parent().parent().parent().parent();
						//console.log()
						var clsd = parentDiv.find('.'+$( this ).attr('class').split(" ")[0]).length;
						//var clsdm = currenttd.find('.'+$( this ).attr('class').split(" ")[0]).length;
						//console.log("clsd"+clsd+"===clsdm"+clsdm);
						if(clsd>1){
							var cls ='td#'+current_data_td+' .' + $( this ).attr('class').split(" ")[0]+".contents";
						  //      console.log(cls);
							$(cls).each(function(index) {
						//		console.log("index:"+index);
								if(index>0){
									$(this).hide();
								}
							});
				
						}
					});
				});
			}, 500);
			$(document).bind('ajaxSuccess.raCivicrm', function() { //run the main code only after Ajax has successfully downloaded your node
				$(".field--name-field-product-image.field--type-image").once().after($(".ui-dialog-buttonset.form-actions"));
				//$(".ui-dialog-buttonset.form-actions").once().appendTo(".field--name-body");
				$(this).unbind('ajaxSuccess.raCivicrm');
			  });
			var current_url = settings.path.currentPath;
			var url_segment = current_url.split( '/' );
			//console.log(url_segment);
			// Make Sure Code only run for admin - Start
			// Start - This code is to open edit button on page and on change to fix shipping recalculate button issue in admin.
			if(url_segment[0]=='admin' && url_segment[1]=='commerce'){
				setTimeout(function(){
					var temp_link = $(".field--name-uid .field__item > a").attr('href');
					var order_number_redirect = "?dest=/admin/commerce/orders/"+url_segment[3]+"/edit";
					if(temp_link){
						var lik = '<li><a href="/upload/tax-doc-upload-member'+temp_link+order_number_redirect+'" class=\'use-ajax\'  data-dialog-type=\'modal\' >Upload Tax Document</a></li>';
						$("ul.tabs.primary").once().append(lik);
					}
				}, 1000);
			}
			// End
			// civicrm price set left and right
			//console.log('manoj in js');
			$(".crm-profile-id-248", context).hide(); 
			$(".crm-profile-id-248", context).once().appendTo(".additional_attendee_includes_meals_for_1_additional_attendee_-section");
			
			$(document).on('click', '.Table_Top-content input', function (e) {
			var selected = $(".Table_Top-content input[type='radio']:checked");
			selectedVal = '';
			if (selected.length > 0) {
					selectedVal = selected.val();
			}
			if(selectedVal=='2401'){
					$(".crm-profile-id-248", context).show();
				}else{
					if($('#price_1137', context).val()==''){
							$(".crm-profile-id-248", context).hide();
							$("#custom_740,#custom_741", context).val('');
						}
					
					}
		});
	
			
			
			$('#price_1137', context).keyup(function(e) {
				//if (e.which != 8 && e.which != 0 && (e.which < 48 || e.which > 57) ) {
				//	alert('Please enter numbers only');
					//$("#errmsg").html("Digits Only").show().fadeOut("slow");
				//	$(".crm-profile-id-248", context).hide();
				//	$("#custom_740,#custom_741", context).val('');
					
				//}else 
				
				if($(this).val()==""){
						$(".crm-profile-id-248", context).hide();
						$("#custom_740,#custom_741", context).val('');
				}else{
					$(".crm-profile-id-248", context).show();
				}
			});
      $('#price_1222', context).keyup(function(e) {
          $("#error_price_1222", context).remove();
  			if($(this).val()=="" || $(this).val()<50){
          $(this).css("border", "1px solid red");
          $("#_qf_Main_upload-bottom", context).attr("disabled", true);
          $(this).after( "<span id='error_price_1222' style='color:red'>Please enter 50 license minimum.<br></span>" );
          //alert('Please enter 50 licence minimum.');
  		  }else{
          $(this).css("border", "1px solid #ccc");
          $("#_qf_Main_upload-bottom", context).attr("disabled", false);
          $("#error_price_1222", context).remove();
        }
			});
					
			$('.crm-section.sponsorship_fee_per_series-section .crm-form-checkbox').each(function() {
                            if ( $(this).attr('data-amount') == '100.000000000' || $(this).attr('data-amount') == '75.000000000') {
                                    $(this).parent().parent().addClass('left-column');
                           }else if ( $(this).attr('data-amount') == '200.000000000' || $(this).attr('data-amount') == '150.000000000') {
                                    $(this).parent().parent().addClass('middle-column');
                            }else{
                                    $(this).parent().parent().addClass('last-column');
                            }
                            
                        });
                        setTimeout(function(){
                                $( ".left-column" ).once().wrapAll( "<div class='left-box' style='width: 30%; float:left;'><b>Sponsorship fee for congregations with under 400 members</b></div>" );
                                $( ".middle-column" ).once().wrapAll( "<div class='middle-box' style='width: 30%; float:left;'><b>Sponsorship fee for congregations with 400+ members</b></div>" );
                                $( ".last-column" ).once().wrapAll( "<div class='right-box' style='width: 40%; float:left;'><b>Annual sponsorship fee</b></div>" );
                        }, 1000);
                                        
                         $('.crm-section.eit_ratzon_2022-section .crm-form-checkbox').each(function(index) {
                            if ( index == 0 ) {
                                $(this).parent().parent().parent().css('width','100%');
                                $(this).parent().parent().parent().css('display','block');
                            }
                            if ( index >= 0 && index <=2) {
                                    $(this).parent().parent().addClass('left-column1');
                            }else if ( index >= 3 && index <=9) {
                                    $(this).parent().parent().addClass('middle-column1');
                            }else{
                                    $(this).parent().parent().addClass('last-column1');
                            }
                            //console.log("Loop Index is: "+index);
                            $(this).parent().parent().addClass(index);
                        });
                        setTimeout(function(){
                                $( ".left-column1" ).once().wrapAll( "<div class='left-box' style='width: 100%; float:left;padding-bottom:20px'><b>Sessions for Rabbis in New Positions</b></div>" );
                                $( ".middle-column1" ).once().wrapAll( "<div class='middle-box' style='width: 50%; float:left;'><b>Sessions for Rabbis at Any Age/Stage/Career Area</b></div>" );
                                $( ".last-column1" ).once().wrapAll( "<div class='right-box' style='width: 50%; float:left;'><b>Leadership Series - Rabbis & Lay Leaders Together</b></div>" );
                        }, 1000);
			// END
			// Start - Membership search
			if(url_segment[0]=='user' && url_segment[1]=='usersearch' && settings.utility_common.usertype!='Admin'){
				setTimeout(function(){
					$('#edit-ra-membership-status-20 option').each(function() {
						if ( $(this).val() == 'member' || $(this).val() == 'widow') {
						}else{
							$(this).remove();
						}
					});
					//$('#edit-ra-membership-status-20 option[value="X"]').remove();
				}, 2000);
			}
			// End
			setTimeout(function(){
                        var active_menu = $('.l-main .block--ra-custom-leftbar ul.left_side_bar > li.active',context).length;
                         $('.l-main .block--ra-custom-leftbar ul.left_side_bar > li',context).each(function () {
                                    if(active_menu==0){
                                        $(this).show();
                                         console.log($(this).attr('class')+ "= Parent =="+active_menu);
                                        //$(this).addClass('open');
                                    }else{
                                        //$(this).addClass('close');
                                        //console.log($(this).attr('class')+ "= Child =="+active_menu);
                                       if($(this).attr('class')=='active'){
                                            $(this).show();
                                            console.log($(this).attr('class')+ "= SHOW=="+active_menu);
                                        }else{
                                            $(this).hide();
                                            console.log($(this).attr('class')+ "= HIDE=="+active_menu);
                                        } 
                                    }
                                   //console.log($(this).attr('class')+ "==="+active_menu);
                          });
                          $('.l-main .block--ra-custom-leftbar ul.left_side_bar > ul',context).hide();
                      }, 1000);
                      
			$('nav ul li ul li a',context).each(function () {
          //console.log($(this));
					if($(this).text()=='Articles'){
						$(this).attr('href','/cj/archive/articles');
					}	
				
					if($(this).text()=='issues'){
						$(this).attr('href','/cj/archive/issues');
					}	
						
			});
			// This code is to open edit button on page and on change to fix shipping recalculate button issue in admin.
			if(url_segment[0]=='admin' && url_segment[1]=='commerce'){
				$("#edit-title-0-value").val("Shipment - "+url_segment[3]);
				if(url_segment[4]=='edit1'){
					$("#block-racustomcommerceaddress").once().prependTo("#edit-billing-profile-0");
					$("[id^=edit-billing-profile-0-profile-edit-button]",context).once().trigger('mousedown');
					// Call if shipping address Change from dropdown
					$("#edit-billing-profile-0-profile .available-profiles", context).change(function () {
						setTimeout(function(){
							$("[id^=edit-billing-profile-0-profile-edit-button]",context).once().trigger('mousedown');
						}, 2000);
					});
				}
                                if(url_segment[4]=='shipments'){
					$("#block-racustomcommerceaddress").once().prependTo("#edit-shipping-profile-0");
                                        //console.log($("[id^=edit-shipping-profile-0-profile-edit-button]",context));
					$("[id^=edit-shipping-profile-0-profile-edit-button]",context).once().trigger('mousedown');
					// Call if shipping address Change from dropdown
					$("#edit-shipping-profile-0-profile .available-profiles", context).change(function () {
						setTimeout(function(){
							$("[id^=edit-shipping-profile-0-profile-edit-button]",context).once().trigger('mousedown');
						}, 2000);
					});
				}
				
				//$("[id^=edit-field-teshu-sa-category-target-id-shs-0-1]",context).once().prepend('<label>Sub Category</label>');
				$(document).on('change', '#old_address', function (e) {
					var fn = $("option:selected", this).attr('fn');
					var gn = $("option:selected", this).attr('gn');
					var comp = $("option:selected", this).attr('comp');
					var add1 = $("option:selected", this).attr('add1');
					var add2 = $("option:selected", this).attr('add2');
					var city = $("option:selected", this).attr('city');
					var zip = $("option:selected", this).attr('zip');
					var phone = $("option:selected", this).attr('phone');
					var state = $("option:selected", this).attr('state');
					if(url_segment[4]=='edit1'){
						$("[id^=edit-billing-profile-0-profile-address-0-address-given-name]",context).val(fn);
						$("[id^=edit-billing-profile-0-profile-address-0-address-family-name]",context).val(gn);
						$("[id^=edit-billing-profile-0-profile-address-0-address-organization]",context).val(comp);
						$("[id^=edit-billing-profile-0-profile-address-0-address-address-line1]",context).val(add1);
						$("[id^=edit-billing-profile-0-profile-address-0-address-address-line2]",context).val(add2);
						$("[id^=edit-billing-profile-0-profile-address-0-address-locality]",context).val(city);
						$("[id^=edit-billing-profile-0-profile-address-0-address-postal-code]",context).val(zip);
						$("[id^=edit-billing-profile-0-profile-field-phone-number-0-value]",context).val(phone);
						$("[id^=edit-billing-profile-0-profile-address-0-address-administrative-area]",context).val(state);
						//$("[id^=edit-billing-profile-0-profile-address-0-address-country-code]",context).val('US');
					}
					if(url_segment[4]=='shipments'){
						$("[id^=edit-shipping-profile-0-profile-address-0-address-given-name]",context).val(fn);
						$("[id^=edit-shipping-profile-0-profile-address-0-address-family-name]",context).val(gn);
						$("[id^=edit-shipping-profile-0-profile-address-0-address-organization]",context).val(comp);
						$("[id^=edit-shipping-profile-0-profile-address-0-address-address-line1]",context).val(add1);
						$("[id^=edit-shipping-profile-0-profile-address-0-address-address-line2]",context).val(add2);
						$("[id^=edit-shipping-profile-0-profile-address-0-address-locality]",context).val(city);
						$("[id^=edit-shipping-profile-0-profile-address-0-address-postal-code]",context).val(zip);
						$("[id^=edit-shipping-profile-0-profile-field-phone-number-0-value]",context).val(phone);
						$("[id^=edit-shipping-profile-0-profile-address-0-address-administrative-area]",context).val(state);
						$("[id^=edit-shipping-profile-0-profile-address-0-address-country-code]",context).val('US');
					}
				});
			}
			// End
			
			// START - This will be executed onload to hide double title if only single node on the term page.
			if ($(".block-system-main-block div.views-row", context).length == 1) {
				var title = $(".block-system-main-block div.views-row h2:first").text();
				//console.log(title);
				$(".block-system-main-block div.views-row h2:first").hide();
				$("h1.page-title").html(title);
			}
			// END
			// Civi Crm profile view
			$("div#row-email_Primary", context).insertBefore($("div#row-custom_7", context));
			$("div#row-email_1", context).insertBefore($("div#row-phone_1", context));
			$('#email-1', context).keyup(function(e) {
                          $('.page-user #email-Primary', context).val($(this).val());
                        });
			$('.page-user #editrow-email-Primary',context).hide();
                         var hide_paypal_button = ', #edit-civicrm-1-contribution-1-contribution-payment-processor-id-1';
			 $(document).on('click', '#edit-civicrm-1-contribution-1-contribution-total-amount--wrapper input'+hide_paypal_button, function (e) {
                        setTimeout(function(){       
		        $("#payment_information .paypal_button_info-section", context).remove();
                        $("#payment_information ._qf_Payment_upload_express-section", context).remove();
			}, 1000);
		         });

			//$("div#row-email_1", context).hide();
                        // END
			// START - Civicrm Due Page
			//console.log($(".credit_card_info-section #credit_card_number"));
			$(".credit_card_info-section #credit_card_number").removeClass( "required" ); 
			$(".credit_card_info-section #credit_card_exp_date_M").removeClass( "required" ); 
			$(".credit_card_info-section #credit_card_exp_date_Y").removeClass( "required" ); 
			$(".credit_card_info-section #cvv2").removeClass( "required" ); 
			$(".paypal_button_info-section .description").html('Fill in the credit card and billing information on this form and click Continue at the bottom of the page.'); 
 
			$(".civirm-user-profile-edit #editrow-custom_63").hide();
			$("#priceset-div").show();
			$("#pricesetTotal", context).hide();
			$("div#editrow-custom_211", context).prepend($("div.email-5-section", context));
			$("div#editrow-custom_221", context).append($("div.price_set-section", context));
			$("div#editrow-custom_221", context).append($("div.other_amount-content", context));
			$("#crm-container.crm-container form fieldset.crm-profile-name-Donation legend", context).hide();
			//$("#crm-container.crm-container form fieldset.payment_options-group legend", context).hide();
			$("div.contribution_amount-content", context).css("margin-top", "13px");
			$(".contribution_amount-section .label label", context).html('Contribution Amount<span title="This field is required." class="crm-marker"> *</span>');
			var arr = ["price_231", "1"];
			$("#CIVICRM_QFID_0_20", context).attr("price", JSON.stringify(arr));
			// END
			// Start Code for ticket=585
			
			if(current_url == 'civicrm/contact/search' || current_url == 'civicrm/contact/search/advanced'){ 
				$('select',context).each(function () {
					checkExportDropDownvalue(this.id, this.val);
				});
				$('.crm-form-select',context).change(function() {
					checkExportDropDownvalue($(this).attr('id'), $(this).val());            
			  });
        $("[id^=phone_phone_type_id]").parent().css("display", "none");
				function checkExportDropDownvalue(drop_down_id, drop_down_value){
					sliced_id = drop_down_id.substring(0,drop_down_id.length - 1);
					first_drop_down_id = sliced_id+'1';
					first_drop_down_value = $('#'+first_drop_down_id).val();
					if(drop_down_value == 'phone' || first_drop_down_value == 'phone'){            
						third_drop_down_id = sliced_id+'3';
						$('#'+third_drop_down_id).hide();
					}
				}
        
			}
      
      
			// END
			//$('.page-civicrm #option11_wrapper').doubleScroll();
			//web_form_table_element.wrap( "<div class='view-content'></div>" );
			
			var web_form_table_element = $('.webform-element-plugin-table');
			web_form_table_element.once().addClass('views-table');
			var permissions_table_element = $('.permissions');
			permissions_table_element.once().addClass('views-table');
			var civicrm_wrapper = $('#crm-main-content-wrapper');
			civicrm_wrapper.addClass('views-table');
			
            var table_element = $('.views-table').parent();
			table_element.doubleScroll();
			
			$.fn.exists = function(){ return this.length > 0; }
			if ($('.doubleScroll-scroll-wrapper').exists()) { 
			table_element.mousewheel(function(event, delta) {
			   this.scrollLeft -= (delta * 50);
			   this.scrollRight -= (delta * 50);
			   this.style.transition = '1s';
			   event.preventDefault();
			});
			}		
		}
	};
	
	if($(window).width() >= 901 ){
			$('.l-region--sidebar-first ul.menu > li.menu-item--expanded > a').on('click', function(e) {
				e.preventDefault();
				  $('.l-region--sidebar-first ul.menu > li.menu-item--expanded > a');
				  $(this).siblings('.l-region--sidebar-first ul.menu > li.menu-item--expanded > ul.menu').slideToggle('500');        
			});
			$('.l-region--sidebar-first ul.menu > li.menu-item--expanded').on('click', function(e) {
				  $(this).toggleClass("li-parent");
			     });
			}
		
}(jQuery, Drupal, drupalSettings));
(function ($) {
		
		$(document).on('change', '#uc-ad', function (e) {
			$("[id^=edit-billing-profile-0-profile-edit-button]").trigger('mousedown');
			var state = $("option:selected", this).attr('state');
			//console.log(state);
			//state = 'NY';
			$(".administrative-area").val(state);
			$('.administrative-area option:contains('+state+')').prop('selected',true);
			
			
		});
		
	$(document).on('click', '.form-radio', function (e) {
		if (this.name == "shipping_information[shipments][0][shipping_method][0]") {
			$('#edit-actions-next').prop('disabled', false);
			$('.recalculate_help_text').remove();
			if ($("[id^=edit-shipping-information-shipments-0-shipping-method-0-2-default]").is(":checked")) {
				$('.ups-mi-help-text').html('');
				$('.ups-mi-help-text1').html('');
				$("[id^=edit-shipping-information-shipments-0-shipping-method]").next('label').append('<div class=\"ups-mi-help-text1\"> (does not ship to PO Box)</div>');
				$(".ups-mi-help-text1").first().hide();
				$("[id^=edit-shipping-information-shipments-0-shipping-method-0-2-default]").next('label').append('<div class=\"ups-mi-help-text\">( Please be advised that packages shipped using this shipping method have limited tracking ability and are not insured and may take 6-8 weeks to arrive. )</div>');
				$('.hover_bkgr_fricc').show();
			} else {
				$('.ups-mi-help-text').remove();
			}
			//var pageURL = window.location.pathname; 
			//$("#commerce-checkout-flow-multistep-default").submit(); 
			//$('#commerce-checkout-flow-multistep-default').attr('action', pageURL);  
			//window.location = pageURL;
		}
	});
	var linkRewriter = function(a, b) {
    $('.block-system-main-block a').each(function() {
		
        $(this).attr('href', $(this).attr('href').replace(a, b));
        console.log($(this).attr('href'));
    });
};

// Hide the completed date field for status other than completed in bulk order status update
selected_state = $("#edit-default-value-input-state").val();
if(selected_state != 'completed'){
  $('.custom_completed_date').hide();
}
$("#edit-default-value-input-state").on('change', function(){
  selected_status = $("#edit-default-value-input-state").val();
  if(selected_status == 'completed'){
    $('.custom_completed_date').show();
  } else{
    $('.custom_completed_date').hide();
  }
});
//linkRewriter('www.rabbinicalassembly.org/', 'www.rastage.org/');
})(jQuery);


