/**
 * DO NOT EDIT THIS FILE.
 * See the following change record for more information,
 * https://www.drupal.org/node/2815083
 * @preserve
 **/

(function ($, Drupal, drupalSettings) {	
	Drupal.behaviors.raCivicrm = {
		attach: function (context, settings) {
			var current_url = settings.path.currentPath;
			var url_segment = current_url.split( '/' );
			//console.log(url_segment);
			// Make Sure Code only run for admin - Start
			// Start - This code is to open edit button on page and on change to fix shipping recalculate button issue in admin.
			if(url_segment[0]=='admin' && url_segment[1]=='commerce'){
				setTimeout(function(){
					var temp_link = $(".field--name-uid .field__item > a").attr('href');
					var order_number_redirect = "?dest=/admin/commerce/orders/"+$("h1.page-title").text();
					if(temp_link){
						var lik = '<li><a href="/upload/tax-doc-upload-member'+temp_link+order_number_redirect+'" class=\'use-ajax\'  data-dialog-type=\'modal\' >Upload Tax Document</a></li>';
						$("ul.tabs.primary").once().append(lik);
					}
				}, 2000);
			}
			// End
			// This code is to open edit button on page and on change to fix shipping recalculate button issue in admin.
			if(url_segment[0]=='admin' && url_segment[1]=='commerce'){
				$("#edit-title-0-value").val("Shipment - "+url_segment[3]);
				$("#edit-shipping-profile-0-profile-edit-button").once().trigger('mousedown');
				// Call if shipping address Change from dropdown
				$("#edit-shipping-profile-0-profile .available-profiles", context).change(function () {
					setTimeout(function(){
					$("[id^=edit-shipping-profile-0-profile-edit-button]",context).once().trigger('mousedown');
					//console.log(settings.path.currentPath);
					}, 2000);
				});
			}
			// End
			
 			// START - This will be executed onload to hide double title if only single node on the term page.
			if ($(".block-system-main-block div.views-row", context).length == 1) {
				var title = $(".block-system-main-block div.views-row h2:first").text();
				//console.log(title);
				$(".block-system-main-block div.views-row h2:first").hide();
				$("h1.page-title").html(title);
			}
			// END 
			// civicrm price set left and right
			$('.crm-section.sponsorship_fee_per_series-section .crm-form-checkbox').each(function() {
								console.log($(this).attr('data-amount')+"==="+ "Manoj");
						if ( $(this).attr('data-amount') == '100.000000000' || $(this).attr('data-amount') == '75.000000000') {
							$(this).parent('div').addClass('left-column');
						}else{
							$(this).parent('div').addClass('right-column');
						}
					});
			// END
			// START - Civicrm Due Page
			$(".civirm-user-profile-edit #editrow-custom_63").hide();
			$("#priceset-div").show();
			$("#pricesetTotal", context).hide();
			$("div#editrow-custom_211", context).prepend($("div.email-5-section", context));
			$("div#editrow-custom_221", context).append($("div.price_set-section", context));
			$("div#editrow-custom_221", context).append($("div.other_amount-content", context));
			$("#crm-container.crm-container form fieldset.crm-profile-name-Donation legend", context).hide();
			//$("#crm-container.crm-container form fieldset.payment_options-group legend", context).hide();
			$("div.contribution_amount-content", context).css("margin-top", "13px");
			$(".contribution_amount-section .label label", context).html('Contribution Amount<span title="This field is required." class="crm-marker"> *</span>');
			var arr = ["price_231", "1"];
			$("#CIVICRM_QFID_0_20", context).attr("price", JSON.stringify(arr));
			// END
		}
	};
	
	if($(window).width() >= 901 ){
			$('.l-region--sidebar-first ul.menu > li.menu-item--expanded > a').on('click', function(e) {
				e.preventDefault();
				  $('.l-region--sidebar-first ul.menu > li.menu-item--expanded > a');
				  $(this).siblings('.l-region--sidebar-first ul.menu > li.menu-item--expanded > ul.menu').slideToggle('500');        
			});
			$('.l-region--sidebar-first ul.menu > li.menu-item--expanded').on('click', function(e) {
				  $(this).toggleClass("li-parent");
			     });
			}
		
}(jQuery, Drupal, drupalSettings));
